'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.DedicacionesSoap")>  _
    Public Interface DedicacionesSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asig del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDedication", ReplyAction:="*")>  _
        Function getDedication(ByVal request As ServiceReference1.getDedicationRequest) As ServiceReference1.getDedicationResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDedication", ReplyAction:="*")>  _
        Function getDedicationAsync(ByVal request As ServiceReference1.getDedicationRequest) As System.Threading.Tasks.Task(Of ServiceReference1.getDedicationResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getDedicationRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getDedication", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.getDedicationRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.getDedicationRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getDedicationRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public asig As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal asig As String)
            MyBase.New
            Me.asig = asig
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getDedicationResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getDedicationResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.getDedicationResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.getDedicationResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getDedicationResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public getDedicationResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getDedicationResult As Integer)
            MyBase.New
            Me.getDedicationResult = getDedicationResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DedicacionesSoapChannel
        Inherits ServiceReference1.DedicacionesSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DedicacionesSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.DedicacionesSoap)
        Implements ServiceReference1.DedicacionesSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_DedicacionesSoap_getDedication(ByVal request As ServiceReference1.getDedicationRequest) As ServiceReference1.getDedicationResponse Implements ServiceReference1.DedicacionesSoap.getDedication
            Return MyBase.Channel.getDedication(request)
        End Function
        
        Public Function getDedication(ByVal asig As String) As Integer
            Dim inValue As ServiceReference1.getDedicationRequest = New ServiceReference1.getDedicationRequest()
            inValue.Body = New ServiceReference1.getDedicationRequestBody()
            inValue.Body.asig = asig
            Dim retVal As ServiceReference1.getDedicationResponse = CType(Me,ServiceReference1.DedicacionesSoap).getDedication(inValue)
            Return retVal.Body.getDedicationResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_DedicacionesSoap_getDedicationAsync(ByVal request As ServiceReference1.getDedicationRequest) As System.Threading.Tasks.Task(Of ServiceReference1.getDedicationResponse) Implements ServiceReference1.DedicacionesSoap.getDedicationAsync
            Return MyBase.Channel.getDedicationAsync(request)
        End Function
        
        Public Function getDedicationAsync(ByVal asig As String) As System.Threading.Tasks.Task(Of ServiceReference1.getDedicationResponse)
            Dim inValue As ServiceReference1.getDedicationRequest = New ServiceReference1.getDedicationRequest()
            inValue.Body = New ServiceReference1.getDedicationRequestBody()
            inValue.Body.asig = asig
            Return CType(Me,ServiceReference1.DedicacionesSoap).getDedicationAsync(inValue)
        End Function
    End Class
End Namespace
